---
- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Show join debug print
  ansible.builtin.debug:
    msg:  "kubeadm join {{  hostvars[groups['kube_masters'][0]].join_path }} --token {{  hostvars[groups['kube_masters'][0]].join_token }} --discovery-token-ca-cert-hash sha256:{{  hostvars[groups['kube_masters'][0]].discovery_token_ca_cert_hash }} --control-plane --certificate-key {{  hostvars[groups['kube_masters'][0]].certificate_key }}"


- name: Join control nodes
  when: not kubeadm_ca.stat.exists
  ansible.builtin.shell:
    cmd: "kubeadm join {{  hostvars[groups['kube_masters'][0]].join_path }} --token {{  hostvars[groups['kube_masters'][0]].join_token }} --discovery-token-ca-cert-hash sha256:{{  hostvars[groups['kube_masters'][0]].discovery_token_ca_cert_hash }} --control-plane --certificate-key {{  hostvars[groups['kube_masters'][0]].certificate_key }}"

# Add link
- name: Add directory for config file
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: 700

- name: Add link for config file
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    state: link

- name: Kubelet enable
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
