[kube_masters]
cp01.test ansible_host=192.168.122.11
cp02.test ansible_host=192.168.122.48
cp03.test ansible_host=192.168.122.156

[kube_workers]
w01.test ansible_host=192.168.122.243

[kube_cluster:children]
kube_masters
kube_workers