[kube_masters]
cp01.test ansible_host=10.0.11.50
cp02.test ansible_host=10.0.11.51
cp03.test ansible_host=10.0.11.52

[kube_workers]
w01.test ansible_host=10.0.11.53

[kube_cluster:children]
kube_masters
kube_workers