[kube_masters]
cp01.test ansible_host=192.168.122.12
cp02.test ansible_host=192.168.122.80
cp03.test ansible_host=192.168.122.193

[kube_workers]
w01.test ansible_host=192.168.122.192

[kube_cluster:children]
kube_masters
kube_workers