[kube_masters]
hybrid.dev.cp01 ansible_host=10.0.11.64
hybrid.dev.cp02 ansible_host=10.0.11.66
hybrid.dev.cp03 ansible_host=10.0.11.68

[kube_workers]
hybrid.dev.w01 ansible_host=10.0.11.61

[kube_cluster:children]
kube_masters
kube_workers
