- name: Get current kubelet version
  shell: "kubectl get nodes {{ ansible_fqdn }} -o=jsonpath='{.status.nodeInfo.kubeletVersion}'"
  register: version_current
  changed_when: false

- name: Normalize versions for safe comparison
  set_fact:
    current_ver_clean: "{{ version_current.stdout | regex_replace('^v', '') }}"
    target_ver_clean: "{{ full_kube_version_for_upgrade | regex_replace('^v', '') }}"

- name: Check if upgrade is needed
  block:
  - name: Show skip message
    debug:
      msg: "Node {{ ansible_fqdn }} is already on version {{ current_ver_clean }}. Skipping upgrade."

  - name: Stop execution for this host
    meta: end_host
  when: current_ver_clean == target_ver_clean

# - name: Backup etcd data
#   shell: |
#     ETCDCTL_API=3 etcdctl \
#     --endpoints=https://127.0.0.1:2379 \
#     --cacert=/etc/kubernetes/pki/etcd/ca.crt \
#     --cert=/etc/kubernetes/pki/etcd/server.crt \
#     --key=/etc/kubernetes/pki/etcd/server.key \
#     snapshot save /var/lib/etcd-backup/backup-{{ ansible_date_time.iso8601_basic_short }}.db
#   environment:
#     ETCDCTL_API: 3
#   register: etcd_backup

- name: Run kubeadm upgrade plan
  command: kubeadm upgrade plan v{{ kube_version }}
  register: upgrade_plan

- name: Apply kubeadm upgrade
  command: "kubeadm upgrade apply v{{ full_kube_version_for_upgrade }} -y"
  register: upgrade_apply
  async: 600
  poll: 10

- name: Show upgrade result
  debug:
    var: upgrade_apply.stdout_lines

- name: Unhold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
  - kubelet
  - kubectl

- name: Upgrade kubelet and kubectl
  apt:
    name:
    - "kubelet={{ full_kube_version_for_upgrade }}*"
    - "kubectl={{ full_kube_version_for_upgrade }}*"
    state: present
    allow_change_held_packages: yes

- name: Run kubeadm upgrade node
  command: kubeadm upgrade node

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: Hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
  - kubelet
  - kubectl
  - kubeadm
