- name: Cordon master node (Mark unschedulable)
  command: "kubectl cordon {{ ansible_fqdn }}"
  delegate_to: "{{ groups['kube_masters'][0] }}"
  failed_when: false

- name: Unhold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
  - kubelet
  - kubectl

- name: Upgrade kubelet and kubectl
  apt:
    name:
    - "kubelet={{ full_kube_version_for_upgrade }}*"
    - "kubectl={{ full_kube_version_for_upgrade }}*"
    state: present
    allow_change_held_packages: yes

- name: Run kubeadm upgrade node
  command: kubeadm upgrade node

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: Hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
  - kubelet
  - kubectl
  - kubeadm

- name: Uncordon master node (Mark schedulable)
  command: "kubectl uncordon {{ ansible_fqdn }}"
  delegate_to: "{{ groups['kube_masters'][0] }}"

