- name: Get current kubelet version
  shell: "kubectl get nodes {{ ansible_fqdn }} -o=jsonpath='{.status.nodeInfo.kubeletVersion}'"
  register: version_current
  delegate_to: "{{ groups['kube_masters'][0] }}"
  changed_when: false
  run_once: false

- name: Normalize versions for safe comparison
  set_fact:
    current_ver_clean: "{{ version_current.stdout | regex_replace('^v', '') }}"
    target_ver_clean: "{{ full_kube_version_for_upgrade | regex_replace('^v', '') }}"

- name: Check if upgrade is needed
  block:
  - name: Show skip message
    debug:
      msg: "Node {{ ansible_fqdn }} is already on version {{ current_ver_clean }}. Skipping upgrade."

  - name: Stop execution for this host
    meta: end_host
  when: current_ver_clean == target_ver_clean

- name: Drain node (Shell fallback)
  delegate_to: "{{ groups['kube_masters'][0] }}"
  # --disable-eviction
  shell: "kubectl drain {{ ansible_fqdn }} --ignore-daemonsets --delete-emptydir-data"
  register: drain_result
  changed_when: "'drained' in drain_result.stdout"

# - name: Drain node
#   kubernetes.core.k8s_drain:
#     name: "{{ ansible_fqdn }}"
#     delete_emptydir_data: true
#     disable_eviction: false
#     state: drain
#   delegate_to: "{{ groups['kube_masters'][0] }}"

- name: Unhold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
  - kubelet
  - kubectl

- name: Upgrade kubelet and kubectl
  apt:
    name:
    - "kubelet={{ full_kube_version_for_upgrade }}*"
    - "kubectl={{ full_kube_version_for_upgrade }}*"
    state: present
    allow_change_held_packages: yes

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: Hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
  - kubelet
  - kubectl
  - kubeadm

- name: Uncordon node
  delegate_to: "{{ groups['kube_masters'][0] }}"
  shell: "kubectl uncordon {{ ansible_fqdn }}"
  register: uncordon_result
  changed_when: "'uncordoned' in uncordon_result.stdout"

# - name: Uncordon node (Module fallback)
#   kubernetes.core.k8s_drain:
#     name: "{{ ansible_fqdn }}"
#     state: uncordon
#   delegate_to: "{{ groups['kube_masters'][0] }}"
