- name: Drain node (Shell fallback)
  delegate_to: "{{ groups['kube_masters'][0] }}"
  shell: "kubectl drain {{ ansible_fqdn }} --ignore-daemonsets --delete-emptydir-data"
  register: drain_result
  changed_when: "'drained' in drain_result.stdout"

# - name: Drain node
#   kubernetes.core.k8s_drain:
#     name: "{{ ansible_fqdn }}"
#     delete_emptydir_data: true
#     disable_eviction: false
#     state: drain
#   delegate_to: "{{ groups['kube_masters'][0] }}"

- name: Unhold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
  - kubelet
  - kubectl

- name: Upgrade kubelet and kubectl
  apt:
    name:
    - "kubelet={{ full_kube_version_for_upgrade }}*"
    - "kubectl={{ full_kube_version_for_upgrade }}*"
    state: present
    allow_change_held_packages: yes

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: Hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
  - kubelet
  - kubectl
  - kubeadm

- name: Uncordon node
  delegate_to: "{{ groups['kube_masters'][0] }}"
  shell: "kubectl uncordon {{ ansible_fqdn }}"
  register: uncordon_result
  changed_when: "'uncordoned' in uncordon_result.stdout"

# - name: Uncordon node (Module fallback)
#   kubernetes.core.k8s_drain:
#     name: "{{ ansible_fqdn }}"
#     state: uncordon
#   delegate_to: "{{ groups['kube_masters'][0] }}"
