# Add link
- name: Add directory for config file
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: Add link for config file
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    state: link



- name: Copy Helm 3.17.1 version last before v4
  ansible.builtin.copy:
    src: ./files/helm
    dest: /usr/local/bin/helm
    mode: '0755'
  when: inventory_hostname == groups['kube_masters'][0]

